#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <stdbool.h>
#include <string.h>

typedef enum {
  TOKEN_LEFT_P,
  TOKEN_RIGHT_P,
  TOKEN_ASSIGNMENT,
  TOKEN_SEMICOLON,
  TOKEN_MULTIPLY,
  TOKEN_DIVIDE,
  TOKEN_MOD,
  TOKEN_ADD,
  TOKEN_SUBTRACT,
  TOKEN_EQUAL,
  TOKEN_NOT_EQUAL,
  TOKEN_GREATER_THAN,
  TOKEN_GREATER_THAN_EQUAL,
  TOKEN_LESS_THAN,
  TOKEN_LESS_THAN_EQUAL,
  TOKEN_IF,
  TOKEN_THEN,
  TOKEN_ELSE,
  TOKEN_BEGIN,
  TOKEN_END,
  TOKEN_PROGRAM,
  TOKEN_WHILE,
  TOKEN_DO,
  TOKEN_IDENTIFIER,
  TOKEN_STRING,
  TOKEN_AS,
  TOKEN_INT, 
  TOKEN_BOOL,
  TOKEN_WRITE_INT,
  TOKEN_READ_INT,
  TOKEN_COMMENT
} token_t;

const char* token_names[] = {
  "TOKEN_LEFT_P",
  "TOKEN_RIGHT_P",
  "TOKEN_ASSIGNMENT",
  "TOKEN_SEMICOLON",
  "TOKEN_MULTIPLY",
  "TOKEN_DIVIDE",
  "TOKEN_MOD",
  "TOKEN_ADD",
  "TOKEN_SUBTRACT",
  "TOKEN_EQUAL",
  "TOKEN_NOT_EQUAL",
  "TOKEN_GREATER_THAN",
  "TOKEN_GREATER_THAN_EQUAL",
  "TOKEN_LESS_THAN",
  "TOKEN_LESS_THAN_EQUAL",
  "TOKEN_IF",
  "TOKEN_THEN",
  "TOKEN_ELSE",
  "TOKEN_BEGIN",
  "TOKEN_END",
  "TOKEN_PROGRAM",
  "TOKEN_WHILE",
  "TOKEN_DO",
  "TOKEN_IDENTIFIER",
  "TOKEN_STRING",
  "TOKEN_AS",
  "TOKEN_INT", 
  "TOKEN_BOOL",
  "TOKEN_WRITE_INT",
  "TOKEN_READ_INT",
  "TOKEN_COMMENT"
};

token_t scan_token(FILE *fp){
  	int current_char = fgetc(fp);

    



}